title: Hearst Lab
desc: data visualization, search interfaces, machine learning, natural language processsing
keywords: Hearst, Marti Hearst, Hearst Lab, UC Berkeley
permalink: pretty
markdown: kramdown
base_name: 's19' # could change this to a subdomain later, like /f17